### ISSUE TITLE
New tutorial for: How to use PromptNode in a pipeline

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-tutorials#113]
**Describe the tutorial you would like to see here**
As a follow up to the tutorial mentioned in #112 I suggest we have a second one where we:
- Use the `PromptNode` as a node in a full pipeline
- As an example, build a retrieval augmented qa pipeline
- Display how you would use the `Shaper`

[x] I've checked the existing tutorials

**Comment by Giriteja** [comment]
How to Train an QA model or NER model using Promtnode?

**Comment by TuanaCelik** [comment]
Hey @Giriteja - `PromptNode` is designed to use various LLMs that are able to consume instructions. If you would like to train a QA model I suggest looking into the `FARMReader` that has a `train()` function.

You can _use_ the `PromptNode` for QA though.

**Comment by prasad4fun** [comment]
> 

Hi @TuanaCelik, how to end to end finetune models like RAG where multiple components like retriever and generator involved. is there a way to train pipelines?
In tutorial 2 I could see FARMReader can be used to train individual models, but not sure how to train RAG in tutorial 7.

**Comment by prasad4fun** [comment]
> > 
> 
> Hi @TuanaCelik, how to end to end finetune models like RAG where multiple components like retriever and generator involved. is there a way to train pipelines? In tutorial 2 I could see FARMReader can be used to train individual models, but not sure how to train RAG in tutorial 7.

@bilgeyucel Could you confirm if #141 include any reference to above question, i have read through commit and couldn't find any references.

**Comment by bilgeyucel** [comment]
Hi @prasad4fun, sorry I missed your comment here before merging the PR. #141 doesn't include information about your question; it is about using PromptNode in a pipeline.
 
About your question, Haystack doesn't support the training of generative models. If you want to improve your model, you can either train FARMReader as in tutorial 2 or instead of using RAGenerator, you can use Seq2SeqGenerator or OpenAIAnswerGenerator as models for these generators are much better. You can also use PromptNode by following the new tutorial: [Creating a Generative QA Pipeline with PromptNode](https://haystack.deepset.ai/tutorials/22_pipeline_with_promptnode). 

Feel free to open a discussion point on [haystack](https://github.com/deepset-ai/haystack) repository if you have more questions. We might miss out on the comments on closed issues here 🙌
