### ISSUE TITLE
Nightly tests are not failing when they're supposed to be

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-tutorials#212]
After introducing a new dependency 'inference' with https://github.com/deepset-ai/haystack/pull/5147, almost all tutorials (the ones with FARMReader and EmbeddingRetriever) are supposed to fail, but they don't. This prevents us from noticing existing bugs

* Is the docker image `deepset/haystack:base-cpu-main` generated correctly?
* Is it cached somewhere?

**Comment by bogdankostic** [comment]
I don't think this is about the docker image, but about the github workflow for the nightly runs. We install `espnet` as a dependency [here](https://github.com/deepset-ai/haystack-tutorials/blob/81c5cbde9ad45fd5a5cfa0b2a3efd9e7ae1f05dd/.github/workflows/nightly.yml#L57), which has `torch` as a requirement - that's why doing inference is working without a problem.

**Comment by bilgeyucel** [comment]
Thanks @bogdankostic, this is really helpful for solving the mystery! :D
